# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: about
    weight: 20
  - name: News
    url: post
    weight: 30
  - name: People
    url: people
    weight: 40
  - name: Projects
    url: projects
    weight: 50
  - name: Prospective Students
    url: ProspectiveStudents
    weight: 60
  - name: Publications
    url: publication
    weight: 70
  - name: Teaching
    url: teaching
    weight: 80
  - name: DEI
    url: dei
    weight: 90
  - name: Letters of Rec
    url: LoRs
    weight: 100
  - name: Contact
    url: contact
    weight: 110
  - name: More
    url: more
    weight: 120
